<?php

/**
 * @file
 * Contains om.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function om_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the om module.
    case 'help.page.om':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Open meetings version 4.0') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function om_theme() {
  return [
    'om' => [
      'render element' => 'children',
    ],
  ];
}
